name: Run Component and Unit tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Get pnpm store path
        id: pnpm-cache-path
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Upload pnpm store
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-store
          path: ${{ env.STORE_PATH }}

  unit-tests:
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Download pnpm store
        uses: actions/download-artifact@v4
        with:
          name: pnpm-store
          path: ~/.local/share/pnpm/store

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm test

  component-tests:
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Download pnpm store
        uses: actions/download-artifact@v4
        with:
          name: pnpm-store
          path: ~/.local/share/pnpm/store

      - name: Install dependencies
        run: pnpm install

      - name: Install Cypress binary
        run: pnpm exec cypress install

      - name: Run component tests
        run: pnpm test-component:headless

  e2e-tests:
    needs: setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Download pnpm store
        uses: actions/download-artifact@v4
        with:
          name: pnpm-store
          path: ~/.local/share/pnpm/store

      - name: Install dependencies
        run: pnpm install

      - name: Build Next.js app
        run: pnpm build

      - name: Install Cypress binary (macOS)
        if: runner.os == 'macOS'
        run: pnpm exec cypress install

      - name: Install Cypress binary (Windows)
        if: runner.os == 'Windows'
        run: pnpm exec cypress install

      - name: Run E2E tests (macOS)
        if: runner.os == 'macOS'
        run: |
          pnpm start &
          npx wait-on http://localhost:3000
          pnpm test-e2e:headless

      - name: Run E2E tests (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Start-Process -FilePath "pnpm" -ArgumentList "start" -NoNewWindow
          npx wait-on http://localhost:3000
          pnpm test-e2e:headless

      - name: Run Cypress tests (Linux)
        if: runner.os == 'Linux'
        uses: cypress-io/github-action@v6
        with:
          start: pnpm start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 60
          command: pnpm test-e2e:headless
